### ISSUE TITLE
About Sqlite zstd with java

### ISSUE THREAD

**Issue by watersoft123** [biaocy/dotfiles#1]
Sorry, I couldn't find a suitable place to send you this message.
I saw your issue in  [sqlite zstd](https://github.com/phiresky/sqlite-zstd/issues/7) searched all the way here. I am developing an Android app, but not using Java, but using [B4A](https://www.b4x.com/b4a.html). I want to compress my sqlite database using zstd method and access it, but I am not very familiar with Java. Therefore, I wonder if it is possible to share your interface for accessing zstd-arm64.so with Java. I would like to package the Java interface and so file together as AAR and call it in B4A. Thank you very much!
My E-mail: tjwater@hotmail.com

**Comment by biaocy** [comment]
Sure
[libsqlite_zstd.so.tar.gz](https://github.com/biaocy/dotfiles/files/15235862/libsqlite_zstd.so.tar.gz)

**Comment by watersoft123** [comment]
> Sure [libsqlite_zstd.so.tar.gz](https://github.com/biaocy/dotfiles/files/15235862/libsqlite_zstd.so.tar.gz)
I have already downloaded it, thank you very much. In Android, it seems that enableLoadExtension cannot be used; I am using [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc), but have not been able to successfully load the extension. Below is the Java code I am using; I am not very familiar with Java, so there may be an error.

> Sure [libsqlite_zstd.so.tar.gz](https://github.com/biaocy/dotfiles/files/15235862/libsqlite_zstd.so.tar.gz)
I have already downloaded it, thank you very much. In Android, it seems that enableLoadExtension cannot be used; I am using [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc), but have not been able to successfully load the extension. Below is the Java code I am using; I am not very familiar with Java, so there may be an error.

private void loadExtension(String extensionName) {
    	SQLiteConfig config = new SQLiteConfig();
    	config.enableLoadExtension(true);
    	try {
            if (connection != null) {
            	Statement stmt = connection.createStatement();
            	stmt.execute("SELECT load_extension('libsqlite_zstd.arm64-v8a')");
                System.out.println("Extension '" + extensionName + "' loaded successfully.");
            } else {
                System.out.println("No connection to SQLite database. Cannot load extension.");
            }
        } catch (SQLException e) {
            System.out.println("Error loading extension '" + extensionName + "': " + e.getMessage());
        }
    }

**Comment by watersoft123** [comment]
> Sure [libsqlite_zstd.so.tar.gz](https://github.com/biaocy/dotfiles/files/15235862/libsqlite_zstd.so.tar.gz)

The issue has been resolved; it was a problem with the path of the so file.
